### ISSUE TITLE
Feature request :)

### ISSUE THREAD

**Issue by GhostieSpook** [AtiLion/BotNeck-Bot#11]
So I saw that you added MAL searching, but I was wondering if you could add Anilist searching aswell. They have a open source discord bot on github that has the api and everything. Im not too good at coding so this is why im asking heh :)

**Comment by AtiLion** [comment]
I have looked at AniList's API before but never tried to add it. I will see what I can do

**Comment by AtiLion** [comment]
Added to the bot in the new 2.0.3 version.

https://github.com/AtiLion/BotNeck-Bot/releases/tag/2.0.3
