### ISSUE TITLE
My purge command doesn't seem to work?

### ISSUE THREAD

**Issue by EricPlayZ** [AtiLion/BotNeck-Bot#15]
So I've made my own purging module, but when I use the command, my command message doesn't even get sent in the chat and it says this:
![image](https://user-images.githubusercontent.com/24963708/88335571-33dbdc00-cd3c-11ea-9a76-8b67d3b94cbc.png)
and then doesn't do absolutely anything else. If I copy one of BotNeck's module code into my purge module (and change the class and command to purge) then the command works fine (say I copied code from calc.botneck.js into my module and changed the class and command names to purge, the command would work fine and it would basically do the same thing as the calc module does, obviously), so at least it's confirmed that there's an issue in my code, but I can't see the issue:
```javascript
class purge {
	constructor() {
		this.permissions = [];
		this.command = "purge";
		this.description = "Purge your own messages";
		this.usage = "purge [number]";
	}

	execute(message, args) {
		// Init
		delete message["content"];
	
		// Validate number of args
		if(BotNeckAPI.getArgumentNumber(args) < 1)
			return message["embed"] = BotNeckAPI.generateError("You need at least 1 argument for this command!");
		if(isNaN(args[0]))
			return message["embed"] = BotNeckAPI.generateError("Specified argument is not a number!");
		if(Number(args[0]) < 0 || Number(args[0]) > 100)
			return message["embed"] = BotNeckAPI.generateError("Message number can't be lower than 0 and higher than 100!");

		
		// Grab the last number(args) of messages in the channel
		const fetchedMsgs = message.channel.fetchMessages({limit: args[0]});
		
		// Filter messages to the user's messages
		const userMsgs = fetchedMsgs.filter(msg => msg.author);
		
		// Get the number of deleted messages
		const deletedMsgsCount = userMsgs.array().length;
		
		// Execute
		message.channel.bulkDelete(userMsgs)
			.catch(error => BotNeckAPI.generateError(`${error}`));
	
		// Send embed
		message["embed"] = {
			title: "Purge",
			type: "rich",
			description: "",
			color: 0x0061ff,
			fields: [
				{
					name: "Number of purged messages",
					value: deletedMsgsCount,
				}
			]
		}
	}
}
```

**Comment by AtiLion** [comment]
The issue is with the following part
```csharp
		// Grab the last number(args) of messages in the channel
		const fetchedMsgs = message.channel.fetchMessages({limit: args[0]});
		
		// Filter messages to the user's messages
		const userMsgs = fetchedMsgs.filter(msg => msg.author);
		
		// Get the number of deleted messages
		const deletedMsgsCount = userMsgs.array().length;
		
		// Execute
		message.channel.bulkDelete(userMsgs)
			.catch(error => BotNeckAPI.generateError(`${error}`));
```

The message object is the object that Discord generates which gets sent to the server. This message usually contains the following 3 fields: content, tts, nonce. More information can be found on [This Link](https://discord.com/developers/docs/resources/channel#create-message)
BotNeck doesn't really offer an indepth Discord API as it's simply designed to intercept the message before it being sent, so that Discord can't really see if it is a self bot or not(this is also the reason why I don't implement things like purging and such).

**Comment by EricPlayZ** [comment]
Oh, interesting. Alright, thanks for the help. Imma close this ig.
