### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by ghost** [AtiLion/BotNeck-Bot#16]
maybe you could add a system where other people can use the bot if their authorized or know the prefix?

**Comment by AtiLion** [comment]
The issue with it is then it's not really a "self-bot" but more of a user bot, with actual user bots, I'm not really sure if there's a decent way of implementation without it being an external program.
This also needs to have the security risks accounted, and while the "authorization" system would work, simply having someone take control over what you say is not a good idea.

**Comment by AtiLion** [comment]
Won't be implemented, closing issue.
