### ISSUE TITLE
Converting command modules

### ISSUE THREAD

**Issue by Hex-ed** [AtiLion/BotNeck-Bot#17]
While I am by no means good at coding, I still try to mess with stuff, and im trying to take a existing command module from another bot and put it into this one, I have converted a bit of the code to try to make it compatible but I cant seem to get it to work, and im wondering if anyone else has tried this or has any idea on how to get it to work, thanks.

**Comment by AtiLion** [comment]
This heavily depends on the bot you took the module from, however due to the high difference between both functionality and the API availability, converting a module is not a simple task and will most likely require a recode of the module. You can feel free to post it here and keep the issue open then based on the module I can either officially add it or attempt to convert it for you.

**Comment by Hex-ed** [comment]
I see what your saying, before I was messing with the code of the other command, it said it required other files from the bot to run, like "discord.js" and a few config files. The main reason I was trying to convert the commands is the fact that almost all other self bots either dont work, or I cant get to install due to me having already installed 10+ versions of python, but mainly if possible I just wanted to see if it can happen so that theres more features for this selfbot.

**Comment by Hex-ed** [comment]
const Discord = require('discord.js');
const customisation = require('../customisation.json');

exports.run = async (client, message, args) => {
    if(args && args.length > 1){
        message.channel.send(`${message.author.username} has paid their respect for **${args.join(' ')}** <:MafuHearty:596554617349865493>`)
    }else{
        message.channel.send(`${message.author.username} has paid their respect <:MafuHearty:596554617349865493>`)
    }
};

exports.conf = {
    enabled: true,
    guildOnly: false,
    aliases: ["eff"],
    permLevel: 0
  };
  
  exports.help = {
    name: 'f',
    description: 'Press F to pay Respekt',
    usage: 'f'
  };
This is the file before I started messing with it, I dont have the file of were I edited it, nut I can still tell you what I changed

**Comment by Hex-ed** [comment]
`const Discord = require('discord.js');
const customisation = require('../customisation.json');

exports.run = async (client, message, args) => {
    if(args && args.length > 1){
        message.channel.send(`${message.author.username} has paid their respect for **${args.join(' ')}** <:MafuHearty:596554617349865493>`)
    }else{
        message.channel.send(`${message.author.username} has paid their respect <:MafuHearty:596554617349865493>`)
    }
};

exports.conf = {
    enabled: true,
    guildOnly: false,
    aliases: ["eff"],
    permLevel: 0
  };
  
  exports.help = {
    name: 'f',
    description: 'Press F to pay Respekt',
    usage: 'f'
  };`
This is the file before I started messing with it, I dont have the file of were I edited it, nut I can still tell you what I changed

**Comment by AtiLion** [comment]
Suggestion has been implemented!
You can find it here: https://github.com/AtiLion/BotNeck-Bot/releases/tag/2.1.0
