### ISSUE TITLE
When taking too long, to give a message back, clyde returns an error.

### ISSUE THREAD

**Issue by legendofmiracles** [AtiLion/BotNeck-Bot#18]
So i am working on a plugin, called cowsay, which sends the first argument, just as cowsay would return it, by using sub processes, to invoke the real cowsay installed on the system. The problem is, the callbacks, on stdout, trigger too slowly, and clyde responds with an error, as seen in the image. ![Image](https://i.imgur.com/BIvEnPJ.png)

I wanted to know, if you could implement something on the api's side, to circumvent this kind of behaviour, and give the plugin a bit more time to respond.

I had one idea, though, the message gets sent normally, and then once cowsay returns something on stdout, the message gets edited and replaced with the output.

Thanks for a response!

**Comment by legendofmiracles** [comment]
I've been trying to get the editing to work, but i haven't been able to get past the 401 unauthorized error, but i am using the function, as seen in backupChat.js
```js
beforeSend: function (xhr) {
     BotNeckAPI.setAuthHeader(xhr, APIKey);
}
```

**Comment by AtiLion** [comment]
Hi! For the response time, I really can't do much about it, requests are handled in such a way where changing the timeout is a bit difficult to do.

The method you described for that is already used for both the "mal" and "anilist" commands. You can find the mal command here: https://github.com/AtiLion/BotNeck-Bot/blob/master/BotNeckModules/mal.botneck.js

When using setAuthHeader you do need to specify beforehand that the module requires this permission, you can also find this in the MAL command here: https://github.com/AtiLion/BotNeck-Bot/blob/master/BotNeckModules/mal.botneck.js#L5 or on line 5.

**Comment by legendofmiracles** [comment]
Ok thanks, i'll look at it tomorrow, and add new comments on new issues. 
Thanks again!

**Comment by legendofmiracles** [comment]
So i managed to get it to work, but i already had the permissions set correctly, the only issue was that i didn't `JSON.stringify()` the data. That managed to solve the issue. 
New issue: the last message sent returns the id from the message before the message i am rn sending, and is like that editing the message sent before the one i actually want to. In your code you use 
```js
BotNeckAPI.nextMessagePost(() => {
      id = BotNeckAPI.getLastUserMessageId();
 });
```
, but that ![cow](https://i.imgur.com/Ldrr3PF.png)

**Comment by AtiLion** [comment]
For message sending the way it works is, you have 2 functions to get the ID with.

getLastUserMessageId and getLastBotMessageId, the user message ID is the ID of the last message event that was caused by the user, even if it is then changed by the command, it still counts as a user triggered message. On the other hand bot message ID is the ID of the message that the bot sends without the user having to do anything, it becomes a bot message as soon as you use setAuthHeader on the request.

With the undefined make sure to have a proper scope, a lot of the time javascript is weird with scopes, so make sure you properly handle them.

**Comment by legendofmiracles** [comment]
Yes, it was  a scope issue, but because of how javascript handles asynchronous functions, and isn't very verbose about it. I managed to fix it, and now it works perfectly, if you want to have a look at the code, you can do that [here](https://github.com/alx365/dots/blob/master/.config/BetterDiscord/plugins/BotNeckModules/cowsay.botneck.js). 

Thanks for the help, helping me making this small cute addon a real thing! I am planning on adding support for cowsay files, such as tux, daemon, and eye ([cowsay(1)](https://linux.die.net/man/1/cowsay)).

![thanks](https://i.imgur.com/gU922ue.png)

**Comment by legendofmiracles** [comment]
Edit: i just replaced cowsay with figlet, and then i can also send figlet messages: 
![image](https://i.imgur.com/h05muI6.png)
