### ISSUE TITLE
Suggestion: Allow spaces in field.name in embeds

### ISSUE THREAD

**Issue by clarkgp** [AtiLion/BotNeck-Bot#19]
Currently, when adding a space in `field.name` (ex. `field.abc def=ghijkl`), it just skips that part thus not appearing when in embed form.

**Comment by AtiLion** [comment]
I don't think I'll be able to add this without it causing issues in the long run, so instead for the embed I'll make it so if you add an _ in the field name it will be converted into a space.

**Comment by AtiLion** [comment]
Suggestion has been implemented in a different way, I will see in the future if this will change for now you can find the work around here: https://github.com/AtiLion/BotNeck-Bot/releases/tag/2.1.0
