### ISSUE TITLE
Make Docs for devs

### ISSUE THREAD

**Issue by zoeleu** [AtiLion/BotNeck-Bot#21]

**Comment by AtiLion** [comment]
Yeah I planned on making it in the Wiki, problem is I never really got the proper time to make the docs. I will do it as soon as I have the time to do it

**Comment by AtiLion** [comment]
Keeping this open for the suggestion

**Comment by zoeleu** [comment]
you could make a fake node module with TypeScript mappings.

**Comment by AtiLion** [comment]
Added in v3, which will be available by the end of the month hopefully
