### ISSUE TITLE
How do I execute commands

### ISSUE THREAD

**Issue by bucket832** [AtiLion/BotNeck-Bot#26]
I have just downloaded this and am starting to play with it I am unable to run commands. When I type in -> then one of the preinstalled commands it returns an error saying the command was not specified
![Screenshot 2021-01-01 210928](https://user-images.githubusercontent.com/66280253/103449386-b2d32a00-4c75-11eb-9fa4-e4fbdb3572f7.png)

**Comment by KewlSage** [comment]
Did you also put the BotNeckBot folder from the repo in your plugins folder?

**Comment by bucket832** [comment]
![Screenshot 2021-01-01 212026](https://user-images.githubusercontent.com/66280253/103449521-40634980-4c77-11eb-9bed-d7dfa6f02b6d.png)
this is how i have it

**Comment by KewlSage** [comment]
Do you have zeres plugin library?

Also if you are using the files directly from the repository try the latest release instead, if you are already using the release files then asking in the discord as well will help you get a quicker response, beyond those i don't know what the issue could be.

**Comment by bucket832** [comment]
I dont have the zeres plugin library and i downloaded it yesterday, so what discord is it

**Comment by KewlSage** [comment]
https://discord.gg/qWVgdxu

**Comment by AtiLion** [comment]
You can try restarting Discord and seeing if that helps. It happens every now and then that the commands aren't detected, no clue why tho.
You can restart it the normal way or have Discord selected and press Ctrl + R

**Comment by bucket832** [comment]
I tried and it didnt help can you just give an example of how to execute a command so i know i am not just typing the command wrong

**Comment by AtiLion** [comment]
Try using ->help

**Comment by bucket832** [comment]
It still says the same error

**Comment by AtiLion** [comment]
Very odd, could you share a screenshot of any errors in the console when BotNeck loads?
To access the console you can use Ctrl + Shift + I and click Console

**Comment by bucket832** [comment]
![Screenshot 2021-01-02 191530](https://user-images.githubusercontent.com/66280253/103469154-27b66a80-4d2f-11eb-8f74-700a58839091.png)
![Screenshot 2021-01-02 191602](https://user-images.githubusercontent.com/66280253/103469155-284f0100-4d2f-11eb-9001-5459acdec0dd.png)
![Screenshot 2021-01-02 191640](https://user-images.githubusercontent.com/66280253/103469156-284f0100-4d2f-11eb-8a3b-37044c839604.png)

**Comment by bucket832** [comment]
I am not sure if thats all of them
I screenshotted the errors after filtering the botneck bot

**Comment by AtiLion** [comment]
Have you downloaded and installed the version from https://github.com/AtiLion/BotNeck-Bot/releases/tag/3.0.1 or did you clone the repo?

**Comment by bucket832** [comment]
I am not sure i downloaded the zip here
![Screenshot 2021-01-02 203241](https://user-images.githubusercontent.com/66280253/103469965-c6e05f80-4d39-11eb-8a25-63247ce03e7a.png)

**Comment by AtiLion** [comment]
Delete all files that you installed for BotNeck and use the version on the link I provided

**Comment by bucket832** [comment]
I did and I am still getting the same error message

**Comment by AtiLion** [comment]
Which Discord client are you using? Canary, normal one or a custom?

**Comment by bucket832** [comment]
I am not sure I havent changed anything about discord except download better discord

**Comment by AtiLion** [comment]
Extremely odd, try running Discord as admin?

**Comment by bucket832** [comment]
When I run it as admin it says I have no plugins

**Comment by AtiLion** [comment]
This is extremely weird, I have never seen something like this. I know where the bug is, I just don't know why it happens. Did the old one work or have you not tried it?

**Comment by bucket832** [comment]
What do you mean by the old one I have only downloaded through the link you sent and where I said earlier

**Comment by AtiLion** [comment]
There was another version before V3, though I assume it would work considering it's not built in the same way. It's loading some things but not others, which I find very odd, I'll try to see if anyone else might have this issue, so far you are the only one. I'll leave this open until I figure something out

**Comment by bucket832** [comment]
Should I try the older version

**Comment by AtiLion** [comment]
Don't know, you can try it if you want

**Comment by bucket832** [comment]
I downloaded version 2.1.0 or 2.0.0 and it works

**Comment by AtiLion** [comment]
Hmm, must be something with the imports on the new system then, I'll have to ask around, I really don't know what it could be

**Comment by AtiLion** [comment]
Hi, could you try the latest version?

**Comment by AtiLion** [comment]
No response, closing issue
