### ISSUE TITLE
Can we use a "friendly" version ?

### ISSUE THREAD

**Issue by Thumuss** [AtiLion/BotNeck-Bot#27]
Discord doesn't allow sending embed, can we just send a text message instead of an embed ?

**Comment by Thumuss** [comment]
I've create when the v2 was release a version without any embed and now it's more complexe. I can recreate it but it would take a long time and if you can create an entry in the config like "TextEverywhere: true or false" would be the greatest. 
An example is in the BotNeckPresets.createInfo, it will check if he can use embed or not and will return the right thing

**Comment by AtiLion** [comment]
I'll see what I can do

**Comment by eksynn** [comment]
> I've create when the v2 was release a version without any embed and now it's more complexe. I can recreate it but it would take a long time and if you can create an entry in the config like "TextEverywhere: true or false" would be the greatest.
> An example is in the BotNeckPresets.createInfo, it will check if he can use embed or not and will return the right thing

I think that for now you can just edit the preset file and make it how you want it, without the embed - shouldn't be too difficult, I don't think

**Comment by Thumuss** [comment]
Yeah it's possible but when there is an update I need to rewrite it, that's why implement it in can be usefull (if you need help i'm here)

**Comment by AtiLion** [comment]
Yeah, I'll see if I can add it soon

**Comment by AtiLion** [comment]
Friendly version has now been added as a "text only" version. See here: https://github.com/AtiLion/BotNeck-Bot/releases/tag/3.0.2

It does have some limitations though, so keep that in mind
