### ISSUE TITLE
plugin crashes better discord

### ISSUE THREAD

**Issue by wrath3k** [AtiLion/BotNeck-Bot#28]
![Screenshot 2021-04-09 222424](https://user-images.githubusercontent.com/70595095/114256988-7acd3880-9982-11eb-9806-df50a7f4deca.png)

**Comment by sanderDijkxhoorn** [comment]
Are you using the latest version of BD?

**Comment by AtiLion** [comment]
This is known for the latest version of BetterDiscord, and there is currently no way of fixing due to them using sandboxing for the plugins. I will be working on the solution that will work outside of BetterDiscord, as I have no intention of playing cat and mouse with them in regards to bypasses.

**Comment by sanderDijkxhoorn** [comment]
It would be sick if you would make a selfbot using like nodejs using the api + gateway and then make a thing so you can put for example help.js in a directory named commands and then when you type !help it will execute that command

**Comment by AtiLion** [comment]
@sanderDijkxhoorn The point of the bot being a plugin is that it isn't easily detectable by Discord, unlike most selfbots were during the banwave Discord did on them. Having a normal self-bot is easily detectable and requires you to have the program running, as well as have nodejs installed. This is just easier and safer for users.

**Comment by sanderDijkxhoorn** [comment]
Hmmm alright

**Comment by AtiLion** [comment]
@wrath3k Until I manage to get the plugin working in standalone, you can use lightcord

**Comment by notcreeperdude** [comment]
> @wrath3k Until I manage to get the plugin working in standalone, you can use lightcord

It appears as if this also doesnt work with lightcord, i cant get it to detect the plugin.

**Comment by AtiLion** [comment]
Fixed in the latest version (3.0.4+)
