### ISSUE TITLE
Revive Maybe?

### ISSUE THREAD

**Issue by Obey23** [AtiLion/BotNeck-Bot#4]
I feel like you should come back to this project, it seems VERY useful and fun to mess with from my experience the past few hours with it. I like what you've made. Maybe there could be a support discord or something so we can ask open questions about the plugin?

**Comment by AtiLion** [comment]
Maybe

**Comment by Obey23** [comment]
Personally, I enjoy the plugin. Allows me to create some simple stuff for discord commands and all.

**Comment by AtiLion** [comment]
For anyone interested, the new version will be released some time tomorrow, if you have any contributions you wish to add or just want to see the progress and new setup you can go to the [recode branch](https://github.com/AtiLion/BotNeck-Bot/tree/recode) and check the code

**Comment by AtiLion** [comment]
New version has been released. It can be found on the following link: https://github.com/AtiLion/BotNeck-Bot/releases/tag/2.0.0

It requires BandagedDiscord!
