### ISSUE TITLE
Its broken lol

### ISSUE THREAD

**Issue by Obey23** [AtiLion/BotNeck-Bot#7]
The plugin's broken, seeing as Discord updated the text box to a new thing that supports live formatting (cant remember the name, starts with a w lmao) but yeah basically needs a rewrite again, or correcting to check the right text box and all.

Hope it does, this was seriously one of my favourite things to play with.

Best regards,
Obey.

**Comment by AtiLion** [comment]
Hi,

I have tested the plugin and can't seem to find any issue with it. Please make sure you are using the latest version of the plugin, if you are make sure the plugin is enabled. It may also be compatibility issues, the plugin is made to support [BandagedBD](https://rauenzi.github.io/BetterDiscordApp/) not the latest version of BetterDiscord. I have tried to add support, but can't seem to get BetterDiscord working. If you still experience any issues after checking what I suggested then please comment back. I'll keep this issue open for 2 days then close it.

Thanks,
AtiLion
